import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { UploadForm } from "~/components/upload-form";
import { AuthShowcase } from "~/components/auth";
import StripePricing from "~/components/payment";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const { data: isSubscribed } = api.subscription.getIsSubscribed.useQuery({
    email: sessionData?.user?.email ?? "",
  });

  const view = sessionData?.user ? (
    isSubscribed ? (
      <UploadForm />
    ) : (
      <StripePricing />
    )
  ) : (
    <AuthShowcase />
  );
  return (
    <>
      <Head>
        <title>QR-AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex h-full flex-col gap-12 px-4 py-8">
          <div className="flex flex-row justify-between">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              QR <span className="text-[hsl(280,100%,70%)]">AI</span>
            </h1>
            <button
              className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
              onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
              {sessionData ? "Sign out" : "Sign in"}
            </button>
          </div>
          <div className="flex h-full w-full grow flex-row items-center justify-center gap-2">
            {view}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;
