import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";

import { api } from "~/utils/api";
import { UploadForm } from "~/components/upload-form";
import WelcomeMessage from "~/components/welcome";
import StripePricing from "~/components/payment";

const Home: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "guest" });
  const { data: sessionData } = useSession();
  return (
    <>
      <Head>
        <title>QR-AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="flex h-full flex-col gap-12 px-4 py-8">
          <div className="flex flex-row justify-between">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              QR <span className="text-[hsl(280,100%,70%)]">AI</span>
            </h1>
            <button
              className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
              onClick={sessionData ? () => void signOut() : () => void signIn()}
            >
              {sessionData ? "Sign out" : "Sign in"}
            </button>
          </div>
          <div className="flex h-full w-full grow flex-row items-center gap-2">
            <div className="h-full max-w-xs grow bg-slate-400">
              <p className="text-2xl text-white">
                {hello.data ? hello.data.greeting : "Loading..."}
              </p>
              <WelcomeMessage />
            </div>
            <div className="h-full w-full bg-green-200">
              {sessionData ? <UploadForm /> : <AuthShowcase />}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  //this is going to be hidden, auth-ed only box to use for the QR code
  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p>{!sessionData ? "Sign in to access your free generations" : ""}</p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
};
